def individual_serial(turbine):
    return {
        "id": str(turbine["_id"]),
        "Dat/Zeit": turbine["Dat/Zeit"],
        "Wind": turbine["Wind"],
        "Rotor": turbine["Rotor"],
        "Leistung": turbine["Leistung"],
        "Azimut": turbine["Azimut"],
        "Prod. 1": turbine["Prod. 1"],
        "Prod. 2": turbine["Prod. 2"],
        "BtrStd 1": turbine["BtrStd 1"],
        "BtrStd 1": turbine["BtrStd 1"],
        "BtrStd 2": turbine["BtrStd 2"],
        "Gen1-": turbine["Gen1-"],
        "Lager": turbine["Lager"],
        "Außen": turbine["Außen"],
        "GetrT": turbine["GetrT"],
        "Status": turbine["Status"],
        "Spann": turbine["Spann"],
        "Spann.1": turbine["Spann.1"],
        "Spann.2": turbine["Spann.2"],
        "Strom-": turbine["Strom-"],        
        "Strom-.1": turbine["Strom-.1"],
        "Strom-.2": turbine["Strom-.2"],
        "CosPh": turbine["CosPh"],
        "Abgabe": turbine["Abgabe"],
        "Bezug": turbine["Bezug"],
        "KH-Zähl1": turbine["KH-Zähl1"],
        "KH-Zähl2": turbine["KH-Zähl2"],
        "KH-DigiE": turbine["KH-DigiE"],
        "KH-DigiI": turbine["KH-DigiI"],
        "KH-Ana-1": turbine["KH-Ana-1"],
        "KH-Ana-2": turbine["KH-Ana-2"],
        "KH-Ana-3": turbine["KH-Ana-3"],
        "KH-Ana-4": turbine["KH-Ana-4"],        
        "turbine_id": turbine["turbine_id"],
    }

def list_serial(turbines):
    return [individual_serial(turbine) for turbine in turbines] 
